### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kimsng** [cadin/xtouch-mini-processing#1]
I am a sound engineer work on the XR18 with PC running Windows Vista for XAIR Edit. 
I have a X-Touch mini and would like to use it to control the XR18.

I am able to install the requirements.txt

C:\xAir>xair-remote.py -l
Connected MIDI Ports:
    X-TOUCH MINI 0

However, when i run the air-remote.py. I got the following error.

C:\xAir>xair-remote.py "X-TOUCH MINI 0"
Found XR18 with firmware 1.17 on IP 192.168.1.1
Error: MIDI port X-TOUCH MINI 0 does not exist!

When I try to have launch the X-Touch Editor, I got another error message.
May I know if I miss anything? Any idea how I can fix it?

C:\xAir>xair-remote.py "X-TOUCH MINI 0"
Found XR18 with firmware 1.17 on IP 192.168.1.1
Traceback (most recent call last):
  File "C:\xAir\xair-remote.py", line 30, in <module>
    midi = MidiController(args.midi_port, state)
  File "C:\xAir\lib\midicontroller.py", line 71, in __init__
    self.inport = open_input(devicename)
  File "C:\Python27\lib\site-packages\mido\backends\backend.py", line 91, in ope
n_input
    return self.module.Input(name, **self._add_api(kwargs))
  File "C:\Python27\lib\site-packages\mido\ports.py", line 161, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "C:\Python27\lib\site-packages\mido\ports.py", line 86, in __init__
    self._open(**kwargs)
  File "C:\Python27\lib\site-packages\mido\backends\rtmidi.py", line 125, in _op
en
    virtual=virtual, api=self.api)
  File "C:\Python27\lib\site-packages\mido\backends\rtmidi.py", line 96, in _ope
n_port
    rt.open_port(port_id)
  File "src/_rtmidi.pyx", line 588, in rtmidi._rtmidi.MidiBase.open_port
  File "src/_rtmidi.pyx", line 223, in rtmidi._rtmidi._cb_error_func
  File "src/_rtmidi.pyx", line 411, in rtmidi._rtmidi._default_error_handler
rtmidi._rtmidi.SystemError: MidiInWinMM::openPort: error creating Windows MM MID
I input port.

Thanks

**Comment by cadin** [comment]
Hi. Is it possible you opened this on the wrong repo? It doesn’t sound like this has anything to do with my code.
